services:
    orders_generator_workspace:
        build: ./
        container_name: orders_generator_workspace
        networks:
            - laradock_frontend
        ports:
            - 3569:3569
        command: npm run serve:dev

networks:
    laradock_frontend:
            external:
               name: laradock_frontend